# TC_001 — Check Shopping List
# Auto-generated by AI Test Engine
# Placeholders — implementations filled during test execution

import pytest
from pytest_bdd import given, when, then, parsers, scenarios
from playwright.sync_api import Page
from pages.heb_com_search_page import HebSearchPage
from pages.heb_com_page import HebHomePage
from utils.web_actions import WebActions

scenarios("../TC_001_check_shopping_list.feature")

# ── New step definitions ─────────────────────────────────────

@then(parsers.parse('I verify the "Shopping List" link is visible'))
def i_verify_the_value_link_is_visible(page: Page):
    # Verify Shopping List link is there
    # Anticipated: verify_link_visible
    WebActions(page).wait_for_visible(HebHomePage.SHOPPING_LISTS_LINK)

@when(parsers.parse('I search for "Cake"'))
def i_search_for_value(page: Page):
    # Search the Cake
    # Anticipated: search_for
    WebActions(page).send_text(HebHomePage.SEARCH_INPUT, 'Cake')
    WebActions(page).press_key(HebHomePage.SEARCH_INPUT, 'Enter')

@then(parsers.parse('I verify the first item name contains "cake"'))
def i_verify_the_first_item_name_contains_value(page: Page):
    # Check the first item name has cake in it
    # Anticipated: verify_item_name_contains
    WebActions(page).wait_for_visible(HebSearchPage.SEARCH_RESULTS_HEADING)
