import pytest
from playwright.sync_api import Page

from pages.heb_com_page import HebHomePage
from pages.heb_com_search_page import HebSearchPage
from utils.data_validator import DataValidator

# Auto-generated by AI Test Engine — TC_002
# Name: Search flower

class TestSearchFlower:

    @pytest.fixture(autouse=True)
    def setup(self, page: Page):
        self.heb_home_page = HebHomePage(page)
        self.heb_search_page = HebSearchPage(page)

    @pytest.mark.ai_generated
    def test_execute(self):
        self.heb_home_page.open()
        # Verify Shopping List link is there
        self.heb_home_page.verify_shopping_lists_link()
        # Search the flower
        self.heb_home_page.search_via_search_input()
        # Check the first item name has Flower in it
        self.heb_search_page.verify_first_item_name_contains_flower()