import json
import os
import re
from datetime import datetime
from pathlib import Path

_root = Path(__file__).parent.parent  # absolute: d:\...\ai-test-engine
REGISTRY_FILE = _root / "test_registry.json"


def _resolve_framework_path() -> Path:
    """Return the absolute path to the Playwright framework directory."""
    raw = os.getenv("PLAYWRIGHT_FRAMEWORK_PATH", "")
    if raw:
        p = Path(raw)
        if not p.is_absolute():
            p = (_root / p).resolve()
        return p
    return (_root.parent / "playwright-framework").resolve()


def _get_tests_dir() -> Path:
    tests_dir = _resolve_framework_path() / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    return tests_dir


def _load_registry() -> dict:
    if REGISTRY_FILE.exists():
        return json.loads(REGISTRY_FILE.read_text(encoding="utf-8-sig"))
    return {"cases": {}}


def _next_tc_id(reg: dict) -> str:
    """Return the lowest available TC ID (fills gaps left by deleted cases)."""
    existing = {k.upper() for k in reg.get("cases", {}).keys()}
    i = 1
    while f"TC_{i:03d}" in existing:
        i += 1
    return f"TC_{i:03d}"


def _save_registry(reg: dict):
    REGISTRY_FILE.write_text(json.dumps(reg, indent=2, ensure_ascii=False), encoding="utf-8")


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")[:40]


def _class_name(text: str) -> str:
    return "".join(w.capitalize() for w in re.split(r"[^a-zA-Z0-9]", text) if w)[:60] or "TestCase"


def _write_test_file(case: dict):
    tests_dir = _get_tests_dir()
    filepath = tests_dir / case["filename"]
    steps = case["steps"]
    actions = case.get("step_actions", [])
    app_url = case["app_url"]
    tc_id = case["id"]
    name = case["name"]

    lines = [
        "import pytest",
        "from playwright.sync_api import Page",
        "",
        f"# Auto-generated by AI Test Engine — {tc_id}",
        f"# Name: {name}",
        f"# URL: {app_url}",
        f"# Steps: {len(steps)}",
        "",
        f"class Test{_class_name(name)}:",
        "",
        "    @pytest.fixture(autouse=True)",
        "    def setup(self, page: Page):",
        "        self.page = page",
        "",
        "    @pytest.mark.ai_generated",
        "    def test_execute(self):",
        f'        self.page.goto("{app_url}", wait_until="domcontentloaded")',
    ]

    for i, step in enumerate(steps):
        a = actions[i] if i < len(actions) else {}
        locator = a.get("playwright_locator", "")
        action = a.get("action", "click")
        value = a.get("value", "")

        lines.append(f"        # Step {i + 1}: {step}")
        if locator:
            if action == "click":
                lines.append(f'        self.page.locator("{locator}").first.click()')
            elif action == "fill":
                lines.append(f'        self.page.locator("{locator}").first.fill("{value}")')
            elif action == "navigate":
                lines.append(f'        self.page.goto("{value}")')
            elif action in ("assert_visible", "assert_text"):
                lines.append(f'        self.page.locator("{locator}").first.wait_for(state="visible")')
            elif action == "select":
                lines.append(f'        self.page.locator("{locator}").first.select_option("{value}")')
            else:
                lines.append(f'        self.page.locator("{locator}").first.click()')
        else:
            lines.append(f"        pass  # TODO: locator pending AI analysis")

    filepath.write_text("\n".join(lines), encoding="utf-8")
    return filepath


def create_test_case(name: str, steps: list, app_url: str,
                     feature_file: str = "", steps_file: str = "", data_file: str = "",
                     write_test_file: bool = False) -> dict:
    reg = _load_registry()
    tc_id = _next_tc_id(reg)
    filename = f"{tc_id}_{_slug(name)}.py"
    case = {
        "id": tc_id,
        "name": name,
        "filename": filename,
        "app_url": app_url,
        "steps": steps,
        "step_actions": [],
        "feature_file": feature_file,
        "steps_file": steps_file,
        "data_file": data_file,
        "gherkin_steps": [],
        "status": "pending",
        "created_at": datetime.now().isoformat(),
    }
    reg["cases"][tc_id] = case
    _save_registry(reg)
    if write_test_file:
        _write_test_file(case)
    return case


def update_test_case(tc_id: str, name: str = None, steps: list = None,
                     app_url: str = None, step_actions: list = None,
                     status: str = None, write_file: bool = True,
                     feature_file: str = None, steps_file: str = None,
                     data_file: str = None, gherkin_steps: list = None) -> dict:
    reg = _load_registry()
    if tc_id not in reg["cases"]:
        raise KeyError(f"{tc_id} not found")
    case = reg["cases"][tc_id]
    if name is not None:
        case["name"] = name
    if app_url is not None:
        case["app_url"] = app_url
    if steps is not None:
        case["steps"] = steps
        case["step_actions"] = []
        case["status"] = "pending"
    if step_actions is not None:
        case["step_actions"] = step_actions
    if status is not None:
        case["status"] = status
    if feature_file is not None:
        case["feature_file"] = feature_file
    if steps_file is not None:
        case["steps_file"] = steps_file
    if data_file is not None:
        case["data_file"] = data_file
    if gherkin_steps is not None:
        case["gherkin_steps"] = gherkin_steps
    _save_registry(reg)
    if write_file:
        _write_test_file(case)
    return case


def delete_test_case(tc_id: str):
    reg = _load_registry()
    if tc_id not in reg["cases"]:
        raise KeyError(f"{tc_id} not found")
    case = reg["cases"].pop(tc_id)
    fw = _resolve_framework_path()

    # Feature file
    _unlink(fw / "features" / case.get("feature_file", ""))

    # Step file — check both generated/ (v5) and flat steps/ (v4)
    steps_file = case.get("steps_file", "")
    _unlink(fw / "features" / "steps" / "generated" / steps_file)
    _unlink(fw / "features" / "steps" / "generated" / (steps_file + ".bak"))
    _unlink(fw / "features" / "steps" / steps_file)

    # Data JSON
    _unlink(fw / "data" / case.get("data_file", ""))

    # Legacy pytest test file
    _unlink(_get_tests_dir() / case.get("filename", ""))

    _save_registry(reg)


def _unlink(path: Path):
    try:
        if path and path.exists():
            path.unlink()
    except Exception:
        pass


def get_all_test_cases() -> list:
    return list(_load_registry()["cases"].values())


def get_test_case(tc_id: str) -> dict:
    reg = _load_registry()
    if tc_id not in reg["cases"]:
        raise KeyError(f"{tc_id} not found")
    return reg["cases"][tc_id]
