[pytest]
testpaths = tests
addopts = --html=reports/html-report/report.html --self-contained-html -v --tb=short -p no:randomly
markers =
    smoke: Smoke tests
    regression: Regression tests
    google: Google search tests
    db: Database tests
    excel: Excel validation tests

log_cli = true
log_cli_level = INFO
log_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
