"""
Writes TC-specific step definition files into features/steps/generated/.

Rules:
  - Implemented step found in catalog → import it, no duplicate
  - Placeholder found in catalog → reuse (import)
  - No match → create placeholder in generated/
  - Never import from other TC-specific generated files
  - Never overwrite implemented shared steps
"""
import logging
import re
from pathlib import Path
from typing import List

from core.models import CatalogItem, MatchResult, NormalizedStep
from providers.storage import atomic_writer

logger = logging.getLogger(__name__)


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")[:40]


def _func_name(step_text: str) -> str:
    clean = re.sub(r'"[^"]+"', "value", step_text)
    clean = re.sub(r"[^a-z0-9]+", "_", clean.lower()).strip("_")
    return clean[:60] or "step"


def _placeholder_body(normalized: NormalizedStep) -> List[str]:
    return [
        "    # NIPACHAN_PLACEHOLDER: true",
        f"    # category: {normalized.category}",
        f"    # raw: {normalized.raw_step}",
        "    raise NotImplementedError('Auto implementation pending')",
    ]


def _build_decorator(keyword: str, step_pattern: str) -> str:
    """Always use the PATTERN (with {placeholders}) so pytest-bdd can extract parameters."""
    if '"' in step_pattern or '{' in step_pattern:
        escaped = step_pattern.replace("'", "\\'")
        return f"@{keyword}(parsers.parse('{escaped}'))"
    return f'@{keyword}("{step_pattern}")'


def _params_from_pattern(pattern: str) -> str:
    params = re.findall(r'\{(\w+)\}', pattern)
    if not params:
        return "page: Page"
    args = ", ".join(f"{p}: str" for p in params)
    return f"page: Page, {args}"


def write(
    framework_path: Path,
    tc_id: str,
    tc_name: str,
    feature_filename: str,
    normalized_steps: List[NormalizedStep],
    match_results: List[MatchResult],
) -> str:
    """Write generated step file. Returns filename."""
    generated_dir = framework_path / "features" / "steps" / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)
    _ensure_init(generated_dir)

    slug = _slug(tc_name)
    filename = f"{tc_id}_{slug}_steps.py"
    filepath = generated_dir / filename
    feature_rel = f"../../{feature_filename}"

    # Shared steps come from conftest.py pytest_plugins — no imports needed here.
    # Only collect new (unmatched) steps that need placeholder definitions.
    shared_used: List[str] = []
    new_step_blocks: List[str] = []
    seen_funcs: set[str] = set()

    for step, result in zip(normalized_steps, match_results):
        if result.matched and result.catalog_item:
            item = result.catalog_item
            if item.source == "shared":
                shared_used.append(f"{step.keyword} {step.step_text}  →  {item.function_name}")
        else:
            kw = step.keyword.lower()
            func = _func_name(step.step_text)
            if func in seen_funcs:
                func = f"{func}_{tc_id.lower()}"
            seen_funcs.add(func)

            params = _params_from_pattern(step.step_pattern)
            decorator = _build_decorator(kw, step.step_pattern)
            block = [
                "",
                decorator,
                f"def {func}({params}):",
            ] + _placeholder_body(step)
            new_step_blocks.extend(block)

    lines = [
        f"# {tc_id} — {tc_name}",
        "# Auto-generated by Nipachan v5",
        "# Shared steps are loaded globally via pytest_plugins in conftest.py",
    ]

    if shared_used:
        lines.append("# Shared steps used:")
        for note in shared_used:
            lines.append(f"#   {note}")

    lines += [
        "",
        "from pytest_bdd import given, when, then, parsers, scenarios",
        "from playwright.sync_api import Page",
        "",
        f'scenarios("{feature_rel}")',
        "",
    ]

    if new_step_blocks:
        lines.append("# ── New step definitions ──────────────────────────────────────")
        lines.extend(new_step_blocks)

    content = "\n".join(lines) + "\n"
    atomic_writer.write_text(filepath, content)
    logger.info("StepFileWriter: wrote %s (%d new placeholders)", filename, len(new_step_blocks))
    return filename


def _module_path(file_path: str) -> str:
    """Convert a file path like 'playwright-framework/features/steps/shared/search_steps.py'
    to 'features.steps.shared.search_steps'."""
    p = file_path.replace("\\", "/")
    # Strip leading framework dir prefix
    for prefix in ("playwright-framework/", "playwright_framework/"):
        if prefix in p:
            p = p[p.index(prefix) + len(prefix):]
            break
    return p.replace("/", ".").removesuffix(".py")


def _ensure_init(directory: Path) -> None:
    init = directory / "__init__.py"
    if not init.exists():
        init.touch()
